'use client';

import { Download, ExternalLink, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { ReportItem } from '@/lib/dashboard/types';
import { formatBytes, formatDate } from '@/lib/utils';
import { PageHeading } from './page-heading';
import { Button } from './ui/button';
import { Card } from './ui/card';

export function ReportsView({ reports }: { reports: ReportItem[] }) {
  const [query, setQuery] = useState('');
  const [type, setType] = useState('All');
  const filtered = useMemo(() => reports.filter((item) =>
    (type === 'All' || item.type === type) && item.name.toLowerCase().includes(query.toLowerCase()),
  ), [query, reports, type]);
  return (
    <>
      <PageHeading title="Reports" description="Latest and historical HTML, PDF, JSON, CSV, and distributable report bundles generated by the automation framework."/>
      <Card className="overflow-hidden">
        <div className="flex flex-wrap gap-2 border-b border-slate-200 p-3">
          <div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={14}/><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-9 w-full rounded-lg border border-slate-300 pl-9 pr-3 text-xs outline-none focus:border-indigo-400" placeholder="Search reports…"/></div>
          <select value={type} onChange={(e) => setType(e.target.value)} className="h-9 rounded-lg border border-slate-300 bg-white px-3 text-xs text-slate-600">{['All', 'PDF', 'HTML', 'JSON', 'CSV', 'ZIP'].map((value) => <option key={value}>{value}</option>)}</select>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[820px] text-left text-xs">
            <thead className="bg-slate-50 text-[10px] text-slate-500"><tr><th className="px-4 py-2.5">Report</th><th className="px-4 py-2.5">Suite</th><th className="px-4 py-2.5">Type</th><th className="px-4 py-2.5">Generated</th><th className="px-4 py-2.5">Size</th><th className="px-4 py-2.5 text-right">Actions</th></tr></thead>
            <tbody>
              {filtered.map((item) => <tr key={item.path} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold text-slate-700">{item.name}</td><td className="px-4 py-3 text-slate-500">{item.suite}</td><td className="px-4 py-3"><span className="rounded bg-indigo-50 px-2 py-1 text-[9px] font-bold text-indigo-700">{item.type}</span></td><td className="px-4 py-3 text-slate-500">{formatDate(item.modifiedAt)}</td><td className="px-4 py-3 text-slate-500">{formatBytes(item.size)}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><a href={`/api/artifacts/${item.path}`} target="_blank"><Button size="sm"><ExternalLink size={12}/>View</Button></a><a href={`/api/artifacts/${item.path}?download=1`}><Button size="sm"><Download size={12}/>Download {item.type}</Button></a></div></td></tr>)}
              {!filtered.length && <tr><td colSpan={6} className="px-4 py-16 text-center text-xs text-slate-400">{reports.length ? 'No reports match this filter.' : 'No reports yet. Run a scan to generate reports.'}</td></tr>}
            </tbody>
          </table>
        </div>
      </Card>
    </>
  );
}
