import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { appConfig } from '../config.js';
import type { AnalyticsRecord, SiteReport } from '../types.js';
import { ensureDir, readJson } from '../utils/fs.js';
import { createLogger } from '../utils/logger.js';
import { completeJson, parseJsonResponse } from './provider.js';

const log = createLogger('spec-generator');
const OUT_DIR = 'tests/generated';

interface GeneratedSpec { filename: string; title: string; steps: string[]; targetUrl: string; }

/**
 * Reads the latest site-report.json and emits runnable Playwright spec stubs to
 * tests/generated/ based on the AI analyzer's recommendedTests, uncovered page
 * categories, and high-traffic pages. Stubs are tagged @generated so they never
 * gate CI until a human reviews and removes test.fixme(). LLM fleshes out steps
 * when a key is configured; otherwise category-based templates are used.
 */
export async function generateSpecsFromReport(): Promise<string[]> {
  const reportPath = join(appConfig.reportsDir, 'site-report.json');
  if (!existsSync(reportPath)) {
    log.warn('No site-report.json — run a scan first.');
    return [];
  }
  const report = await readJson<SiteReport>(reportPath);
  await ensureDir(OUT_DIR);

  const specs = await buildSpecs(report);
  const written: string[] = [];
  for (const spec of specs) {
    const path = join(OUT_DIR, spec.filename);
    await writeFile(path, renderSpec(spec), 'utf8');
    written.push(path);
  }
  log.info(`Generated ${written.length} spec stub(s) in ${OUT_DIR}/.`);
  return written;
}

async function buildSpecs(report: SiteReport): Promise<GeneratedSpec[]> {
  const recommendations = report.ai?.recommendedTests ?? [];
  const topTraffic = topTrafficUrls(report.analytics ?? [], report.baseUrl);

  // Try LLM for concrete steps; fall back to templates.
  const ai = await completeJson(
    'You are an SDET. Given QA recommendations and key URLs, return JSON {"specs":[{"filename":"kebab.spec.ts","title":string,"targetUrl":string,"steps":string[]}]}. Steps are short Playwright actions/assertions in plain English. Max 6 specs, max 6 steps each.',
    { recommendations, keyUrls: topTraffic, baseUrl: report.baseUrl }
  );
  const parsed = parseJsonResponse<{ specs: GeneratedSpec[] }>(ai);
  if (parsed?.specs?.length) return parsed.specs.slice(0, 6);

  // Heuristic templates
  const specs: GeneratedSpec[] = [];
  specs.push({
    filename: 'newsletter-signup.spec.ts', title: 'Newsletter signup happy path', targetUrl: report.baseUrl,
    steps: ['Navigate to the homepage', 'Dismiss cookie banner', 'Locate the newsletter email input in the footer', 'Fill a test email and submit', 'Assert a success/confirmation message is visible']
  });
  specs.push({
    filename: 'site-search.spec.ts', title: 'Site search returns results', targetUrl: report.baseUrl,
    steps: ['Open the search field', 'Type a known product term', 'Submit the search', 'Assert at least one result card is visible', 'Assert the results count is greater than zero']
  });
  for (const url of topTraffic.slice(0, 2)) {
    specs.push({
      filename: `journey-${slug(url)}.spec.ts`, title: `High-traffic journey: ${url}`, targetUrl: url,
      steps: ['Navigate to the page', 'Assert HTTP status < 400', 'Scroll to bottom to trigger lazy content', 'Assert primary CTA is visible and enabled', 'Assert no console errors of type error']
    });
  }
  return specs.slice(0, 6);
}

function topTrafficUrls(analytics: AnalyticsRecord[], baseUrl: string): string[] {
  const urls = [...analytics].sort((a, b) => b.weight - a.weight).map((record) => record.url);
  return urls.length > 0 ? urls.slice(0, 4) : [baseUrl];
}

const slug = (url: string) => url.replace(/^https?:\/\//, '').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').slice(0, 40) || 'page';

function renderSpec(spec: GeneratedSpec): string {
  const steps = spec.steps.map((step, index) => `    // Step ${index + 1}: ${step}`).join('\n');
  return `import { expect, test } from '../../src/fixtures/index.js';

/**
 * @generated — AI-suggested coverage from analyzer recommendations.
 * Review, implement the steps, then remove test.fixme() to activate.
 * This file is regenerated by \`npm run ai:generate-specs\`; rename it to keep edits.
 */
test.describe('generated coverage @generated', () => {
  test.fixme('${spec.title.replace(/'/g, "\\'")}', async ({ page, dismissOverlays }) => {
    await page.goto('${spec.targetUrl}', { waitUntil: 'domcontentloaded' });
    await dismissOverlays();
${steps}
    expect(page.url()).toContain('${new URL(spec.targetUrl).hostname}');
  });
});
`;
}
